export const Questions = [
    {
      prompt: "What is the capital of France?",
      optionA: "London",
      optionB: "Berlin",
      optionC: "Paris",
      optionD: "Rome",
      answer: "C",
    },
    {
      prompt: "What is the largest ocean in the world?",
      optionA: "Pacific Ocean",
      optionB: "Atlantic Ocean",
      optionC: "Indian Ocean",
      optionD: "Arctic Ocean",
      answer: "A",
    },
    {
      prompt: "What is the square root of 16?",
      optionA: "2",
      optionB: "4",
      optionC: "6",
      optionD: "8",
      answer: "B",
    },
    {
      prompt: "What is the meaning of life?",
      optionA: "42",
      optionB: "The journey, not the destination",
      optionC: "To find happiness",
      optionD: "To make a difference in the world",
      answer: "D",
    },
    {
      prompt: "What is the best way to learn something new?",
      optionA: "By doing it",
      optionB: "By reading about it",
      optionC: "By watching videos about it",
      optionD: "By talking to someone who knows about it",
      answer: "A",
    },
    {
      prompt: "What is the currency of Japan?",
      optionA: "Yen",
      optionB: "Dollar",
      optionC: "Euro",
      optionD: "Pound",
      answer: "A",
    },
    {
      prompt: "Who wrote 'The Great Gatsby'?",
      optionA: "Mark Twain",
      optionB: "F. Scott Fitzgerald",
      optionC: "Ernest Hemingway",
      optionD: "J.K. Rowling",
      answer: "B",
    },
    {
      prompt: "Which planet is known as the 'Red Planet'?",
      optionA: "Venus",
      optionB: "Jupiter",
      optionC: "Mars",
      optionD: "Neptune",
      answer: "C",
    },
    {
      prompt: "What is the chemical symbol for gold?",
      optionA: "Go",
      optionB: "Gd",
      optionC: "Au",
      optionD: "Ag",
      answer: "C",
    },
    {
      prompt: "What is the capital of Australia?",
      optionA: "Sydney",
      optionB: "Melbourne",
      optionC: "Canberra",
      optionD: "Brisbane",
      answer: "C",
    },
  ];
  